# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end

target 'Runner' do

use_frameworks!


pod 'Firebase/Core'
pod 'Firebase/Firestore'

end