name: cue
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.1
  firebase_dynamic_links: ^0.5.3
  image_picker: ^0.6.7+4
  firebase_storage: ^4.0.1
  video_player: ^0.10.11+1
  path_provider: ^1.6.11
  camera: ^0.5.8+2
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.14.1+3
  flutter_spinkit: ^4.1.2+1
  firebase_core: ^0.5.0+1
  flutter_launcher_icons: ^0.7.5
  pedantic: ^1.9.0
  screen:
    
  flutter:

    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/splash.png
  #   - images/a_dot_ham.jpeg



