name: cue
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.1
  firebase_dynamic_links: ^0.5.3
  image_picker: ^0.6.7+4
  firebase_storage: ^4.0.1
  video_player: ^0.10.11+1
  path_provider: ^1.6.11
  camera: ^0.5.8+2
#  camera: ^0.6.3+2
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.14.1+3
  flutter_spinkit: ^4.1.2+1
  firebase_core: ^0.5.0+1
  flutter_launcher_icons: ^0.7.5
  pedantic: ^1.9.0
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  splashscreen: ^1.3.5
  fluttertoast: ^7.1.6
  google_fonts: ^1.1.1
  video_player_controls: ^2.1.9
  screen:
  flutter:

    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/cueLogo1.png
   - images/cueLogo.png
   - icons/스크랩.png
   - icons/큐.png
   - icons/구독.png
   - icons/마이.png
   - icons/검색.png
   - icons/메세지.png
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: NotoSansCJK
      fonts:
        - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Light.otf
        - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Medium.otf
        - asset: assets/fonts/NotoSansCJKkr/NotoSansCJKkr-Regular.otf


